#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBAddress
@end

@interface DUBAddress : DUBObject


@property(nonatomic) NSString* address;

@property(nonatomic) NSString* suburb;
/* two digit ISO 3166-1 alpha-2 code 
 */
@property(nonatomic) NSString* country;
/* must be a valid state code for the given country 
 */
@property(nonatomic) NSString* state;
/* must be a valid postcode for the given country [optional]
 */
@property(nonatomic) NSString* postcode;

@end
