#import <Foundation/Foundation.h>
#import "DUBCallConfiguration.h"
#import "DUBError.h"
#import "DUBCall.h"
#import "DUBObject.h"
#import "DUBApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface DUBCallsApi: NSObject

@property(nonatomic, assign)DUBApiClient *apiClient;

-(instancetype) initWithApiClient:(DUBApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DUBCallsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DUBCallsApi*) sharedAPI;
///
///
/// 
/// Get the call configuration for WebRTC client
///
/// @param accountId The account id to get call configuration for
/// 
///
/// @return DUBCallConfiguration*
-(NSNumber*) getCallConfigurationWithAccountId: (NSString*) accountId
    completionHandler: (void (^)(DUBCallConfiguration* output, NSError* error)) handler;


///
///
/// 
/// Create a new call
///
/// @param accountId The account id to create call in
/// @param call The call details to create
/// 
///
/// @return DUBCall*
-(NSNumber*) postCallWithAccountId: (NSString*) accountId
    call: (DUBCall*) call
    completionHandler: (void (^)(DUBCall* output, NSError* error)) handler;



@end
