#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBCall
@end

@interface DUBCall : DUBObject


@property(nonatomic) NSString* _id;
/* number to call 
 */
@property(nonatomic) NSString* number;
/* dubber number to call from [optional]
 */
@property(nonatomic) NSString* dubberNumber;
/* token to use in WebRTC client [optional]
 */
@property(nonatomic) NSString* token;

@end
