#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBCallConfiguration
@end

@interface DUBCallConfiguration : DUBObject

/* Web Socket Proxy to make a WebRTC Call [optional]
 */
@property(nonatomic) NSString* wsProxy;
/* Web Socket Proxy to make a WebRTC Call [optional]
 */
@property(nonatomic) NSString* iceServer;
/* Web Socket Proxy to make a WebRTC Call [optional]
 */
@property(nonatomic) NSString* callerId;

@end
