#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBErrorDetails
@end

@interface DUBErrorDetails : DUBObject


@property(nonatomic) NSNumber* code;

@property(nonatomic) NSArray* /* NSString */ details;

@property(nonatomic) NSString* message;

@property(nonatomic) NSString* moreInfo;

@end
