#import <Foundation/Foundation.h>
#import "DUBError.h"
#import "DUBFindExternalIdentifier.h"
#import "DUBExternalIdentifier.h"
#import "DUBUpdateExternalIdentifier.h"
#import "DUBObject.h"
#import "DUBApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface DUBExternalIdentifiersApi: NSObject

@property(nonatomic, assign)DUBApiClient *apiClient;

-(instancetype) initWithApiClient:(DUBApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DUBExternalIdentifiersApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DUBExternalIdentifiersApi*) sharedAPI;
///
///
/// 
/// Deletes the given external identifier (group authentication required)
///
/// @param externalIdentifierId The external identifier id to delete
/// 
///
/// @return 
-(NSNumber*) deleteExternalIdentifierWithExternalIdentifierId: (NSString*) externalIdentifierId
    completionHandler: (void (^)(NSError* error)) handler;


///
///
/// 
/// Find a resource based on an external identifier (group authentication required)
///
/// @param externalType The external type of the external identifier to find
/// @param serviceProvider The service provider of the external identifier to find
/// @param identifier The identifier of the external identifier to find
/// 
///
/// @return DUBFindExternalIdentifier*
-(NSNumber*) findExternalIdentifierWithExternalType: (NSString*) externalType
    serviceProvider: (NSString*) serviceProvider
    identifier: (NSString*) identifier
    completionHandler: (void (^)(DUBFindExternalIdentifier* output, NSError* error)) handler;


///
///
/// 
/// Get the details for a given external identifier (group authentication required)
///
/// @param externalIdentifierId The external identifier id to get
/// 
///
/// @return DUBExternalIdentifier*
-(NSNumber*) getExternalIdentifierWithExternalIdentifierId: (NSString*) externalIdentifierId
    completionHandler: (void (^)(DUBExternalIdentifier* output, NSError* error)) handler;


///
///
/// 
/// Create a new external identifier for a user (group authentication required)
///
/// @param userId The user id to add external identifier to
/// @param externalIdentifier The external identifier details to create
/// 
///
/// @return DUBExternalIdentifier*
-(NSNumber*) postExternalIdentifierWithUserId: (NSString*) userId
    externalIdentifier: (DUBExternalIdentifier*) externalIdentifier
    completionHandler: (void (^)(DUBExternalIdentifier* output, NSError* error)) handler;


///
///
/// 
/// Update the details for a given external identifier (group authentication required)
///
/// @param externalIdentifierId The external identifier id to update
/// @param externalIdentifier The external identifier details to be updated
/// 
///
/// @return DUBExternalIdentifier*
-(NSNumber*) putExternalIdentifierWithExternalIdentifierId: (NSString*) externalIdentifierId
    externalIdentifier: (DUBUpdateExternalIdentifier*) externalIdentifier
    completionHandler: (void (^)(DUBExternalIdentifier* output, NSError* error)) handler;



@end
