#import <Foundation/Foundation.h>
#import "DUBGroup.h"
#import "DUBError.h"
#import "DUBObject.h"
#import "DUBApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface DUBGroupsApi: NSObject

@property(nonatomic, assign)DUBApiClient *apiClient;

-(instancetype) initWithApiClient:(DUBApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DUBGroupsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DUBGroupsApi*) sharedAPI;
///
///
/// 
/// Get the details for a given group (group authentication required)
///
/// @param groupId The group id to get
/// 
///
/// @return DUBGroup*
-(NSNumber*) getGroupWithGroupId: (NSString*) groupId
    completionHandler: (void (^)(DUBGroup* output, NSError* error)) handler;



@end
