#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBIdentifiedResource
@end

@interface DUBIdentifiedResource : DUBObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* account;

@property(nonatomic) NSString* identifier;

@end
