#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBListNotification.h"


@protocol DUBNotificationList
@end

@interface DUBNotificationList : DUBObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSArray<DUBListNotification>* notifications;

@end
