#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBNotification
@end

@interface DUBNotification : DUBObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* postUrl;

@property(nonatomic) NSString* eventType;

@property(nonatomic) NSNumber* includeData;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* error;

@end
