#import <Foundation/Foundation.h>
#import "DUBError.h"
#import "DUBObject.h"
#import "DUBApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface DUBOAuthApi: NSObject

@property(nonatomic, assign)DUBApiClient *apiClient;

-(instancetype) initWithApiClient:(DUBApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(DUBOAuthApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(DUBOAuthApi*) sharedAPI;
///
///
/// 
/// Revoke an OAuth 2.0 token
///
/// @param token The token to revoke
/// @param clientId The client id associated with the token
/// 
///
/// @return 
-(NSNumber*) revokeTokenWithToken: (NSString*) token
    clientId: (NSString*) clientId
    completionHandler: (void (^)(NSError* error)) handler;



@end
