#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBRecordingTags
@end

@interface DUBRecordingTags : DUBObject


@property(nonatomic) NSArray* /* NSString */ tags;

@end
