#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBRecording
@end

@interface DUBRecording : DUBObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* to;

@property(nonatomic) NSString* toLabel;

@property(nonatomic) NSString* from;

@property(nonatomic) NSString* fromLabel;

@property(nonatomic) NSString* status;

@property(nonatomic) NSArray* /* NSString */ transfers;

@property(nonatomic) NSArray* /* NSString */ additionalParties;

@property(nonatomic) NSNumber* duration;

@property(nonatomic) NSString* callType;

@property(nonatomic) NSString* recordingType;

@property(nonatomic) NSString* channel;
/* Date must be in RFC822 format 
 */
@property(nonatomic) NSString* startTime;
/* Date must be in RFC822 format [optional]
 */
@property(nonatomic) NSString* endTime;

@property(nonatomic) NSArray* /* NSString */ tags;

@property(nonatomic) NSDictionary* /* NSString, NSString */ metadata;

@property(nonatomic) NSDictionary* /* NSString, NSString */ metaTags;

@property(nonatomic) NSString* dateCreated;

@property(nonatomic) NSString* dateUpdated;

@end
