#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBAccount.h"
#import "DUBAddress.h"


@protocol DUBSingleAccount
@end

@interface DUBSingleAccount : DUBAccount


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* group;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* dubberAddress;

@property(nonatomic) NSString* timeZone;

@property(nonatomic) DUBAddress* address;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSDictionary* /* NSString, NSString */ metadata;

@property(nonatomic) NSString* dateCreated;

@property(nonatomic) NSString* dateUpdated;

@property(nonatomic) NSDictionary* /* NSString, NSString */ subresourceUris;

@end
