#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBNotification.h"
#import "DUBUnclaimedMessages.h"


@protocol DUBSingleNotification
@end

@interface DUBSingleNotification : DUBNotification


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* postUrl;

@property(nonatomic) NSString* eventType;

@property(nonatomic) NSNumber* includeData;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* error;

@property(nonatomic) NSString* self;
/* only when notification is for an account [optional]
 */
@property(nonatomic) NSString* account;
/* only when notification is for a group [optional]
 */
@property(nonatomic) NSString* group;

@property(nonatomic) DUBUnclaimedMessages* unclaimedMessages;

@end
