#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBUser.h"


@protocol DUBSingleUser
@end

@interface DUBSingleUser : DUBUser


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* role;

@property(nonatomic) NSString* username;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSNumber* confirmed;

@property(nonatomic) NSString* mobileNumber;

@property(nonatomic) NSString* language;

@property(nonatomic) NSString* dateCreated;

@property(nonatomic) NSString* dateUpdated;

@property(nonatomic) NSString* account;

@end
