#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBUnclaimedNotification
@end

@interface DUBUnclaimedNotification : DUBObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* notification;

@property(nonatomic) NSNumber* unclaimedMessagesReleased;

@end
