#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBUnclaimedMessages
@end

@interface DUBUnclaimedMessages : DUBObject


@property(nonatomic) NSNumber* count;

@property(nonatomic) NSArray* /* NSString */ errors;

@property(nonatomic) NSString* unclaimedUri;

@end
