#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBUser.h"


@protocol DUBUserList
@end

@interface DUBUserList : DUBObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSArray<DUBUser>* users;

@end
