#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DUBAddress.h"


@protocol DUBUpdateAccount
@end

@interface DUBUpdateAccount : DUBObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* dubberAddress;

@property(nonatomic) NSString* timeZone;

@property(nonatomic) DUBAddress* address;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSDictionary* /* NSString, NSString */ metadata;

@end
