#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBUpdateExternalIdentifier
@end

@interface DUBUpdateExternalIdentifier : DUBObject


@property(nonatomic) NSString* externalType;

@property(nonatomic) NSString* serviceProvider;

@property(nonatomic) NSString* identifier;

@end
