#import <Foundation/Foundation.h>
#import "DUBObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DUBUpdateNotification
@end

@interface DUBUpdateNotification : DUBObject


@property(nonatomic) NSString* postUrl;

@property(nonatomic) NSString* eventType;

@property(nonatomic) NSNumber* includeData;

@end
